import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const json = (data: unknown, status = 200) =>
  new Response(JSON.stringify(data), { status, headers: { 'Content-Type': 'application/json' } });

const fmt = (n: number) => '৳ ' + n.toLocaleString('en-BD');

serve(async (req) => {
  try {
    const {
      recipientEmail, recipientName, period,
      base, bonus, deductions, net, status,
      lateCount, lateDeduction,
    } = await req.json();

    // Load Resend API key from system_settings
    let resendKey = '';
    try {
      const supabase = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
      const { data } = await supabase.from('system_settings').select('value').eq('key', 'smtp_config').single();
      if (data?.value) {
        const cfg = JSON.parse(data.value);
        if (cfg.resend_api_key) resendKey = cfg.resend_api_key;
      }
    } catch (_) {}

    if (!resendKey) resendKey = Deno.env.get('RESEND_API_KEY');

    const statusColor = status === 'PAID' ? '#10b981' : '#f59e0b';
    const statusBg    = status === 'PAID' ? '#f0fdf4' : '#fffbeb';

    const htmlBody = `<!DOCTYPE html>
<html>
<body style="margin:0;padding:24px;background:#f1f5f9;font-family:Inter,Arial,sans-serif">
  <div style="max-width:600px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08)">
    <div style="background:#0f172a;padding:28px 32px;display:flex;align-items:center;gap:14px">
      <div style="width:40px;height:40px;background:#E31E24;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:20px;font-weight:900;color:#fff">E</div>
      <div><p style="margin:0;font-size:20px;font-weight:900;color:#fff"><span style="color:#E31E24">Exord</span> Online</p><p style="margin:3px 0 0;font-size:11px;color:#94a3b8">Human Resources Management</p></div>
    </div>
    <div style="padding:28px 32px 0">
      <p style="font-size:22px;font-weight:900;color:#0f172a;margin:0">Salary Slip</p>
      <p style="font-size:13px;color:#64748b;margin:6px 0 20px">${period}</p>
      <p style="font-size:14px;color:#475569;margin:0 0 20px">Dear <strong>${recipientName}</strong>,<br>Your salary details for <strong>${period}</strong> are below.</p>
      <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;margin-bottom:16px">
        <tr style="background:#f0fdf4"><td style="padding:12px 16px;font-size:13px;color:#475569;border-bottom:1px solid #dcfce7">Basic Salary</td><td style="padding:12px 16px;font-size:13px;font-weight:700;color:#0f172a;text-align:right;border-bottom:1px solid #dcfce7">${fmt(base)}</td></tr>
        <tr style="background:#f0fdf4"><td style="padding:12px 16px;font-size:13px;color:#475569;border-bottom:1px solid #dcfce7">Bonus / Allowances</td><td style="padding:12px 16px;font-size:13px;font-weight:700;color:#16a34a;text-align:right;border-bottom:1px solid #dcfce7">+${fmt(bonus)}</td></tr>
        <tr style="background:#fff5f5"><td style="padding:12px 16px;font-size:13px;color:#475569;border-bottom:1px solid #fecaca">Total Deductions${lateCount > 0 ? ` (incl. ${lateCount} late = ${fmt(lateDeduction)})` : ''}</td><td style="padding:12px 16px;font-size:13px;font-weight:700;color:#dc2626;text-align:right;border-bottom:1px solid #fecaca">-${fmt(deductions)}</td></tr>
        <tr style="background:#0f172a"><td style="padding:14px 16px;font-size:14px;font-weight:900;color:#fff;text-transform:uppercase">Net Payable</td><td style="padding:14px 16px;font-size:20px;font-weight:900;color:#E31E24;text-align:right">${fmt(net)}</td></tr>
      </table>
      <div style="text-align:center;margin-bottom:24px"><span style="display:inline-block;padding:8px 24px;border-radius:100px;background:${statusBg};border:2px solid ${statusColor};color:${statusColor};font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:2px">Payment Status: ${status}</span></div>
    </div>
    <div style="padding:20px 32px;background:#f8fafc;border-top:1px solid #e2e8f0">
      <p style="margin:0;font-size:11px;color:#94a3b8;line-height:1.7">Generated by <strong>Exord Online HRM</strong>. Do not reply to this email.</p>
    </div>
  </div>
</body>
</html>`;

    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${resendKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        from: 'Exord Online HRM <onboarding@resend.dev>',
        to: [recipientEmail],
        subject: `Your Salary Slip — ${period}`,
        html: htmlBody,
      }),
    });

    const result = await res.json();
    if (!res.ok) return json({ error: result.message || JSON.stringify(result) }, 500);
    return json({ success: true });

  } catch (err: any) {
    return json({ error: err.message || String(err) }, 500);
  }
});
