ALTER TABLE employees
  ADD COLUMN IF NOT EXISTS avatar_url text,
  ADD COLUMN IF NOT EXISTS base_salary numeric(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS device_id text,
  ADD COLUMN IF NOT EXISTS father_name text,
  ADD COLUMN IF NOT EXISTS mother_name text,
  ADD COLUMN IF NOT EXISTS nid text,
  ADD COLUMN IF NOT EXISTS present_address text,
  ADD COLUMN IF NOT EXISTS permanent_address text,
  ADD COLUMN IF NOT EXISTS doc_deadline timestamptz,
  ADD COLUMN IF NOT EXISTS must_change_password boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS gender text,
  ADD COLUMN IF NOT EXISTS blood_group text,
  ADD COLUMN IF NOT EXISTS dress_size text,
  ADD COLUMN IF NOT EXISTS date_of_birth date,
  ADD COLUMN IF NOT EXISTS phone_official text,
  ADD COLUMN IF NOT EXISTS phone_personal text,
  ADD COLUMN IF NOT EXISTS phone_alternative text,
  ADD COLUMN IF NOT EXISTS religion text,
  ADD COLUMN IF NOT EXISTS marital_status text,
  ADD COLUMN IF NOT EXISTS nationality text,
  ADD COLUMN IF NOT EXISTS emergency_name text,
  ADD COLUMN IF NOT EXISTS emergency_address text,
  ADD COLUMN IF NOT EXISTS emergency_contact text,
  ADD COLUMN IF NOT EXISTS emergency_relation text,
  ADD COLUMN IF NOT EXISTS bank_name text,
  ADD COLUMN IF NOT EXISTS bank_account_number text,
  ADD COLUMN IF NOT EXISTS bank_branch text,
  ADD COLUMN IF NOT EXISTS bank_routing_number text,
  ADD COLUMN IF NOT EXISTS festival_leave_1_choice text,
  ADD COLUMN IF NOT EXISTS festival_leave_2_choice text,
  ADD COLUMN IF NOT EXISTS festival_worked_period integer,
  ADD COLUMN IF NOT EXISTS living_children integer,
  ADD COLUMN IF NOT EXISTS late_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS designation_track text;

CREATE INDEX IF NOT EXISTS idx_employees_email ON employees(lower(email));
CREATE INDEX IF NOT EXISTS idx_employees_status ON employees(status);