/**
 * Legacy Supabase -> self-hosted PostgreSQL mapping.
 *
 * The importer intentionally accepts several legacy column spellings because the
 * old application evolved over time. Source IDs are preserved whenever they are
 * UUIDs; otherwise migration_id_map keeps the relationship stable.
 */
export const TABLE_MAP = {
  users: 'employees',
  units: 'units',
  departments: 'departments',
  attendance: 'attendance',
  leaves: 'leave_requests',
  salaries: 'salary_records',
  loan_requests: 'loan_requests',
  notifications: 'notifications',
  activity_logs: 'audit_logs',
  gps_logs: 'gps_logs',
  pay_scales: 'pay_scales',
  leave_policies: 'leave_policies',
  holidays: 'holidays',
  schedule_change_requests: 'schedule_change_requests',
  weekend_work_permissions: 'weekend_work_permissions',
  duty_roster: 'duty_roster',
  department_delegates: 'department_delegates',
  unit_approvers: 'unit_approvers',
  department_approvers: 'department_approvers',
  role_feature_grants: 'role_capabilities',
  custom_roles: 'custom_roles',
  custom_role_members: 'custom_role_members',
  custom_role_permissions: 'custom_role_permissions',
  user_permissions: 'user_permissions',
  system_settings: 'system_settings',
  profile_change_requests: 'profile_change_requests',
  login_attempts: 'login_attempts',
  conversations: 'conversations',
  conversation_members: 'conversation_members',
  messages: 'messages',
  message_reads: 'message_reads',
  stored_files: 'stored_files',
};

export const IMPORT_ORDER = [
  'roles',
  'units',
  'departments',
  'users',
  'login_attempts',
  'attendance',
  'holidays',
  'pay_scales',
  'leave_policies',
  'leaves',
  'loan_requests',
  'notifications',
  'activity_logs',
  'gps_logs',
  'schedule_change_requests',
  'weekend_work_permissions',
  'duty_roster',
  'department_delegates',
  'unit_approvers',
  'department_approvers',
  'role_feature_grants',
  'custom_roles',
  'custom_role_members',
  'custom_role_permissions',
  'user_permissions',
  'system_settings',
  'profile_change_requests',
  'conversations',
  'conversation_members',
  'messages',
  'message_reads',
  'stored_files',
];
