import { Router } from 'express';
import { db } from '../db/pool.js';
import { requireAuth } from '../auth/middleware.js';

export const dataRouter = Router();
const TABLES = new Set(['login_attempts','notifications','units','departments','users','attendance','custom_role_members','custom_roles','leaves','loan_requests','salaries','activity_logs','pay_scales','gps_logs','user_permissions','role_feature_grants','custom_role_permissions','role_capabilities','leave_policies','system_settings','holidays','duty_roster','department_delegates','unit_approvers','dept_approvers','weekend_work_permissions','profile_change_requests','schedule_change_requests','conversations','conversation_members','messages','message_reads','stored_files']);
const ADMIN_ROLES = new Set(['DEVELOPER','ADMIN','CO_ADMIN','HR','MANAGER']);
const tableMap = (n) => ({users:'employees',leaves:'leave_requests',salaries:'salary_records',activity_logs:'audit_logs',role_feature_grants:'role_capabilities',dept_approvers:'department_approvers'})[n] || n;
const qi = (s) => { if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(s)) throw Object.assign(new Error('Invalid identifier'),{status:400}); return '"'+s+'"'; };
const deny = (req,t,w) => { if(!TABLES.has(t)) throw Object.assign(new Error('Unsupported table'),{status:400}); if(w && !ADMIN_ROLES.has(req.auth.role)) throw Object.assign(new Error('Permission denied'),{status:403}); };
const selectUsers = (fields) => {
  if(fields==='*'||!fields) return 'e.*,r.code AS role,r.code AS role_code,d.name AS department,u.name AS unit_name,e.password_hash AS password,e.employee_code AS employee_id';
  const m={id:'e.id',employee_code:'e.employee_code',email:'e.email',full_name:'e.full_name',name:'e.full_name',phone:'e.phone',password:'e.password_hash',role:'r.code',role_code:'r.code',department:'d.name',department_id:'e.department_id',unit_id:'e.unit_id',unit_name:'u.name',designation:'e.designation',status:'e.status',joining_date:'e.joining_date',weekend_days:'e.weekend_days',avatar_url:'e.avatar_url',avatar:'e.avatar_url',join_date:'e.joining_date',unit_location_lat:'u.latitude',unit_location_lng:'u.longitude',duty_schedule:'e.duty_schedule',documents:'e.documents',native_role:'r.code',base_salary:'e.base_salary',device_id:'e.device_id',father_name:'e.father_name',mother_name:'e.mother_name',nid:'e.nid',present_address:'e.present_address',permanent_address:'e.permanent_address',doc_deadline:'e.doc_deadline',must_change_password:'e.must_change_password',gender:'e.gender',blood_group:'e.blood_group',dress_size:'e.dress_size',date_of_birth:'e.date_of_birth',phone_official:'e.phone_official',phone_personal:'e.phone_personal',phone_alternative:'e.phone_alternative',religion:'e.religion',marital_status:'e.marital_status',nationality:'e.nationality',emergency_name:'e.emergency_name',emergency_address:'e.emergency_address',emergency_contact:'e.emergency_contact',emergency_relation:'e.emergency_relation',bank_name:'e.bank_name',bank_account_number:'e.bank_account_number',bank_branch:'e.bank_branch',bank_routing_number:'e.bank_routing_number',festival_leave_1_choice:'e.festival_leave_1_choice',festival_leave_2_choice:'e.festival_leave_2_choice',festival_worked_period:'e.festival_worked_period',living_children:'e.living_children',late_count:'e.late_count',designation_track:'e.designation_track',created_at:'e.created_at',updated_at:'e.updated_at'};
  return fields.split(',').map(x=>x.trim()).filter(Boolean).map(k=>m[k] ? m[k]+' AS "'+k+'"' : qi(k)).join(',');
};
const legacySelect = (t, fields) => {
  if(t==='users') return selectUsers(fields);
  const maps={
    user_permissions:{user_id:'employee_id',permission:'capability'},
    role_feature_grants:{role:'role_code',feature_key:'capability'},
    custom_role_permissions:{role_id:'role_id',feature_key:'capability'},
    unit_approvers:{unit_id:'unit_id',approver_user_id:'employee_id'},
    dept_approvers:{department:'department_id',approver_user_id:'employee_id'}
  };
  if(maps[t]){
    if(fields==='*') return '*';
    return fields.split(',').map(x=>x.trim()).filter(Boolean).map(k=>maps[t][k]?maps[t][k]+' AS "'+k+'"':qi(k)).join(',');
  }
  if(t==='role_capabilities' && (fields==='role, capabilities' || fields==='role,capabilities')) return 'role_code AS role, jsonb_agg(capability) AS capabilities';
  if(t==='custom_roles' && fields==='id, name, color') return 'id,name,COALESCE(description,\'\') AS color';
  return fields;
};

const bodyMap = (t,b) => { const x={...(b||{})}; const ren=(a,c)=>{if(a in x&&!(c in x)){x[c]=x[a];delete x[a];}}; if(t==='users'){ren('name','full_name');ren('password','password_hash');ren('employee_id','employee_code');} if(t==='leaves') ren('user_id','employee_id'); if(t==='attendance'){ren('user_id','employee_id');ren('timestamp','occurred_at');} if(t==='gps_logs') ren('user_id','employee_id'); if(t==='activity_logs'){ren('user_id','actor_id');ren('timestamp','created_at');} if(t==='weekend_work_permissions'){ren('user_id','employee_id');ren('date','work_date');ren('reviewed_by','reviewed_by_name');} if(t==='duty_roster'){ren('user_id','employee_id');ren('date','duty_date');ren('shift_start','check_in_time');ren('shift_end','check_out_time');ren('shift_label','shift_name');ren('created_by','created_by_name');} if(t==='holidays') ren('date','holiday_date'); if(t==='user_permissions'){ren('user_id','employee_id');ren('permission','capability');} if(t==='role_feature_grants'){ren('role','role_code');ren('feature_key','capability');} if(t==='custom_role_permissions') ren('feature_key','capability'); if(t==='unit_approvers') ren('approver_user_id','employee_id'); if(t==='dept_approvers'){ren('approver_user_id','employee_id');} return x; };
const legacy = (t,r) => { if(!r)return r; const x={...r}; if(t==='users'){x.name=x.full_name;x.password=x.password_hash;x.employee_id=x.employee_code;if(x.role_code)x.role=x.role_code;if(x.department_name)x.department=x.department_name;} if(t==='leaves'){x.user_id=x.employee_id;x.user_name=x.full_name;x.department=x.department_name;} if(t==='salaries'){x.user_id=x.employee_id;x.user_name=x.full_name;} if(t==='activity_logs'){x.user_id=x.actor_id;x.timestamp=x.created_at;} if(t==='attendance'){x.user_id=x.employee_id;x.timestamp=x.occurred_at;} if(t==='gps_logs')x.user_id=x.employee_id; if(t==='user_permissions'){x.user_id=x.employee_id;x.permission=x.capability;} if(t==='role_feature_grants'){x.role=x.role_code;x.feature_key=x.capability;} if(t==='custom_role_permissions')x.feature_key=x.capability; if(t==='unit_approvers')x.approver_user_id=x.employee_id; if(t==='dept_approvers')x.approver_user_id=x.employee_id; if(t==='weekend_work_permissions'){x.user_id=x.employee_id;x.date=x.work_date;x.reviewed_by=x.reviewed_by_name;} if(t==='duty_roster'){x.user_id=x.employee_id;x.date=x.duty_date;x.shift_start=x.check_in_time;x.shift_end=x.check_out_time;x.shift_label=x.shift_name;x.created_by=x.created_by_name;} if(t==='holidays')x.date=x.holiday_date; return x; };
dataRouter.all('/:table', requireAuth, async (req,res,next)=>{
 try { const t=req.params.table; const write=['POST','PATCH','PUT','DELETE'].includes(req.method); deny(req,t,write); const actual=tableMap(t);
  if(req.method==='GET'){
   const vals=[],where=[]; const fields=legacySelect(t,String(req.query.select||'*'));
   for(const [k,v] of Object.entries(req.query)){const m=k.match(/^(eq|neq|gt|gte|lt|lte|ilike|is|in)\[(.+)\]$/);if(!m)continue;const op=m[1],col=m[2];const mapped=t==='users'?(col==='id'?'e.id':col==='email'?'e.email':qi(col)):qi(col);if(op==='in'){where.push(mapped+'=ANY($'+(vals.length+1)+')');vals.push(String(v).split(','));}else if(op==='is'&&String(v)==='null')where.push(mapped+' IS NULL');else{where.push(mapped+' '+({eq:'=',neq:'<>',gt:'>',gte:'>=',lt:'<',lte:'<=',ilike:'ILIKE'})[op]+' $'+(vals.length+1));vals.push(v);}}
   if(t==='notifications'){where.push('recipient_id=$'+(vals.length+1));vals.push(req.auth.employeeId);} if(!ADMIN_ROLES.has(req.auth.role)&&t==='attendance'){where.push('employee_id=$'+(vals.length+1));vals.push(req.auth.employeeId);} if(!ADMIN_ROLES.has(req.auth.role)&&t==='gps_logs'){where.push('employee_id=$'+(vals.length+1));vals.push(req.auth.employeeId);}
   let sql='SELECT '+fields+' FROM '+(t==='users'?'employees e LEFT JOIN roles r ON r.id=e.role_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN units u ON u.id=e.unit_id':qi(actual)); if(where.length)sql+=' WHERE '+where.join(' AND '); if(t==='role_capabilities' && (String(req.query.select||'')==='role, capabilities'||String(req.query.select||'')==='role,capabilities')) sql+=' GROUP BY role_code';
   if(req.query.order){const p=String(req.query.order).split('.');sql+=' ORDER BY '+(t==='users'&&p[0]==='name'?'e.full_name':qi(p[0]))+' '+(p[1]==='desc'?'DESC':'ASC');} sql+=' LIMIT '+Math.min(Math.max(Number(req.query.limit||500),1),1000); const out=await db.query(sql,vals); return res.json({data:out.rows.map(r=>legacy(t,r)),error:null});
  }
  const id=req.query.id; if(req.method==='DELETE'){if(!id)throw Object.assign(new Error('id is required'),{status:400});const out=await db.query('DELETE FROM '+qi(actual)+' WHERE id=$1 RETURNING *',[id]);return res.json({data:out.rows.map(r=>legacy(t,r)),error:null});}
  const body=bodyMap(t,req.body); const keys=Object.keys(body); if(!keys.length)return res.json({data:[],error:null}); const vals=keys.map(k=>body[k]);
  if(req.method==='POST'){const cols=keys.map(qi).join(',');const ph=vals.map((_,i)=>'
  if(!id)throw Object.assign(new Error('id is required'),{status:400}); const sets=keys.map((k,i)=>qi(k)+'=$'+(i+1)).join(',');const out=await db.query('UPDATE '+qi(actual)+' SET '+sets+' WHERE id=$'+(vals.length+1)+' RETURNING *',[...vals,id]);return res.json({data:out.rows.map(r=>legacy(t,r)),error:null});
 }catch(e){next(e);} });+(i+1)).join(',');const conflict=req.query.onConflict?String(req.query.onConflict).split(',').map(qi).join(','):'';const updates=keys.filter(k=>!(String(req.query.onConflict||'').split(',').includes(k))).map((k)=>qi(k)+'=EXCLUDED.'+qi(k)).join(',');const sql='INSERT INTO '+qi(actual)+' ('+cols+') VALUES ('+ph+') '+(conflict?'ON CONFLICT ('+conflict+') DO UPDATE SET '+(updates||qi(keys[0])+'=EXCLUDED.'+qi(keys[0])):'')+' RETURNING *';const out=await db.query(sql,vals);return res.status(201).json({data:out.rows.map(r=>legacy(t,r)),error:null});}
  if(!id)throw Object.assign(new Error('id is required'),{status:400}); const sets=keys.map((k,i)=>qi(k)+'=$'+(i+1)).join(',');const out=await db.query('UPDATE '+qi(actual)+' SET '+sets+' WHERE id=$'+(vals.length+1)+' RETURNING *',[...vals,id]);return res.json({data:out.rows.map(r=>legacy(t,r)),error:null});
 }catch(e){next(e);} });